databases:
  - name: smart-brain-db
    databaseName: smart_brain_db_qy16
    user: fatemabohra
    host: dpg-ci1n1g1mbg56bei96cqg-a
 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: DATABASE_URL
    fromDatabase:
      name: smart-brain-db
      property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50